### ISSUE TITLE
Hello! Did you use Kinect v2 to run this project? I've seen the parameters in some files!

### ISSUE THREAD

**Issue by ghost** [yubaoliu/semantic_slam_floatlazer#1]

**Comment by yubaoliu** [comment]
I do not remember now. Maybe I tried using Kinect v2. Which files you mentioned?

**Comment by ghost** [comment]
> I do not remember now. Maybe I tried using Kinect v2. Which files you mentioned?
@yubaoliu 

OK！please see these file：
  semantic_slam_floatlazer/semantic_slam/kinect_semantic_mapping.rviz
  semantic_slam_floatlazer/semantic_slam/params/semantic_cloud.yaml
  semantic_slam_floatlazer/semantic_slam/params/semantic_cloud_tum.yaml
 
I see you comment words about kinect v2. So I wanna check did you use kinect v2 to run this project.
Thanks for your reply.

**Comment by yubaoliu** [comment]
It seems I also tried kinect v2.

**Comment by ghost** [comment]
@yubaoliu  Thanks for your reply! So if I want to use Kinect V2 to run this project. What command I need input in the terminal, and do I have to change other parameters?
